# Generated by Django 4.1.7 on 2023-03-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_authtoken_token_alter_authtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.TextField(default='4a95ecbc24c7c04e5502d6e595aeda61'),
        ),
    ]
