# Generated by Django 4.1.7 on 2023-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_authtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.TextField(default='4c9b0e56384a324301e563396b3605d3'),
        ),
    ]
